name: Docker Image CI

on:
  [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Set version
        id: version
        run: echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build. -f Dockerfile --tag news-site:${{ env.VERSION }}

      - name: Push the Docker image
        run: |
          docker tag news-site:${{ env.VERSION }} ${{ secrets.DOCKER_HUB_USERNAME }}/news-site:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/news-site:${{ env.VERSION }}
