name: Docker Image CI

on:
  [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build the Docker image
        run: |
          VERSION=$(date +%Y%m%d%H%M%S) # Use the current timestamp as build metadata
          docker build. --file Dockerfile --tag news-site:$VERSION

      - name: Push the Docker image
        run: |
          docker tag news-site:$VERSION ${{ secrets.DOCKER_HUB_USERNAME }}/news-site:$VERSION
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/news-site:$VERSION
